name: Zig

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: zig-ci

    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Set up Zig
        uses: https://codeberg.org/mlugg/setup-zig@v2.2.1
        with:
          use-cache: false

      - name: Show Zig version
        run: zig version

      - name: Build and test
        run: zig build test
